source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MTLAlertView_Example', :exclusive => true do
  pod "MTLAlertView", :path => "../"
end

target 'MTLAlertView_Tests', :exclusive => true do
  pod "MTLAlertView", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
